update docker in old pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -3,22 +3,14 @@ stages:
   - deploy
 
 variables:
-  DOCKER_HOST: tcp://docker:2375
-  DOCKER_TLS_CERTDIR: ""
-  DOCKER_DRIVER: overlay2
-
-.default-docker:
-  image: docker:26.1.4
-  services:
-    - name: docker:26.1.4-dind
-      command: ["--tls=false", "--mtu=1500"]
-  before_script:
-    - echo "$DOCKER_HUB_ACCESS_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
-    - apk add --no-cache nodejs npm bash jq
+  DOCKER_HOST: "unix:///var/run/docker.sock"
 
 build-rest:
   stage: build
-  extends: .default-docker
+  image: docker:26.1.4
+  before_script:
+    - echo $DOCKER_HUB_ACCESS_TOKEN | docker login -u ${DOCKER_HUB_USERNAME} --password-stdin
+    - apk add --no-cache nodejs npm bash jq
   script:
     - cd inferno-games-rest
     - npm run docker:build
@@ -36,7 +28,13 @@ build-rest:
 
 build-web:
   stage: build
-  extends: .default-docker
+  image: docker:26.1.4
+  services:
+    - name: docker:dind
+      command: ["--host=tcp://0.0.0.0:2375", "--mtu=1500"]
+  before_script:
+    - echo $DOCKER_HUB_ACCESS_TOKEN | docker login -u ${DOCKER_HUB_USERNAME} --password-stdin
+    - apk add --no-cache nodejs npm bash jq
   script:
     - cd inferno-games-web
     - npm run docker:build
@@ -56,25 +54,41 @@ deploy:
   stage: deploy
   image: ubuntu:22.04
   before_script:
-    - apt-get update -y
-    - apt-get install -y openssh-client iproute2
+    - apt-get -yq update
+    - apt-get -yqq install openssh-client iproute2 || { echo "SSH client installation failed"; exit 1; }
     - mkdir -p ~/.ssh
+    - install -m 600 -D /dev/null ~/.ssh/id_rsa
     - echo "$STAGE_SERVER_PRIVATE_KEY" | base64 --decode > ~/.ssh/id_rsa
     - chmod 600 ~/.ssh/id_rsa
     - ssh-keyscan -H "$STAGE_SERVER_HOST" >> ~/.ssh/known_hosts
     - export DEPLOY_PATH="/home/$STAGE_SERVER_USER/inferno-games"
   script:
-    - ssh "$STAGE_SERVER_USER@$STAGE_SERVER_HOST" "mkdir -p $DEPLOY_PATH"
-    - |
-      SERVICES=""
-      [ -n "$BUILT_REST" ] && SERVICES="$SERVICES inferno-games-rest"
-      [ -n "$BUILT_WEB" ] && SERVICES="$SERVICES inferno-games-web"
-
-      if [ -n "$SERVICES" ]; then
-        ssh "$STAGE_SERVER_USER@$STAGE_SERVER_HOST" \
-          "cd $DEPLOY_PATH && docker compose pull $SERVICES && docker compose up -d $SERVICES"
+    - echo "Testing SSH connectivity..."
+    - ssh -i ~/.ssh/id_rsa "$STAGE_SERVER_USER@$STAGE_SERVER_HOST" "echo Connected"
+    - ssh -i ~/.ssh/id_rsa "$STAGE_SERVER_USER@$STAGE_SERVER_HOST" "mkdir -p $DEPLOY_PATH"
+    - if [ ! -f docker-compose.yml ]; then echo "docker-compose.yml not found"; exit 1; fi
+    - echo "Checking if docker-compose.yml exists on server..."
+    - if ssh -i ~/.ssh/id_rsa "$STAGE_SERVER_USER@$STAGE_SERVER_HOST" "test -f $DEPLOY_PATH/docker-compose.yml"; then
+        echo "docker-compose.yml already exists on server, skipping copy";
       else
-        echo "No services to deploy"
+        echo "docker-compose.yml not found on server, copying...";
+        scp -i ~/.ssh/id_rsa -r docker-compose.yml "$STAGE_SERVER_USER@$STAGE_SERVER_HOST:$DEPLOY_PATH/.";
+      fi
+    # Only restart services that were actually built
+    - |
+      SERVICES_TO_RESTART=""
+      if [ -n "$BUILT_REST" ]; then
+        SERVICES_TO_RESTART="$SERVICES_TO_RESTART inferno-games-rest"
+      fi
+      if [ -n "$BUILT_WEB" ]; then
+        SERVICES_TO_RESTART="$SERVICES_TO_RESTART inferno-games-web"
+      fi
+      
+      if [ -n "$SERVICES_TO_RESTART" ]; then
+        echo "Restarting services: $SERVICES_TO_RESTART"
+        ssh -i ~/.ssh/id_rsa "$STAGE_SERVER_USER@$STAGE_SERVER_HOST" "cd \"$DEPLOY_PATH\" && docker compose pull $SERVICES_TO_RESTART && docker compose up -d $SERVICES_TO_RESTART"
+      else
+        echo "No services need to be restarted"
       fi
   after_script:
     - rm -rf ~/.ssh
